layout: stacked

repository: EnricoBenedetti/enricobenedetti.github.io

style: dark
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
permalink: /:title/
defaults:
  - scope:
      path: "assets/images/jp-post"
    values:
      image_jp_post: true
projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    - EnricoBenedetti
    - enricobenedetti.github.io
social_media:
  # linkedin: enribene
    mail: enrico.benedetti5@studio.unibo.it"
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
# topics:
#   - name: NLP
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
#   - name: Computer Vision
#   - name: Games
#     web_url: https://github.com/topics/sass
# image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png